/*
  Do not edit this file. It will be overwritten during updates.
*/

const path = require('path')
const projectConfig = require('./projectconfig')
const projectDllModules = require('./projectdllmodules')

const config = Object.assign({}, projectConfig)

config.basePath = process.cwd()

// At this time, the source directory must be directly below the vscode directory.
config.absoluteSourcePath = path.join(config.basePath, config.sourceDir)

// At this time, you must have your node_modules directory in or above the project directory.
// The setting below makes that assumption.
config.node_modulesPath = 'node_modules'

config.stylesheetTypes = []
if (config.useLess) {
  config.stylesheetTypes.push('less')
}
if (config.useSass) {
  config.stylesheetTypes.push('sass')
}
if (config.useCss) {
  config.stylesheetTypes.push('css')
}

config.urlLoaderExtensions = config.strUrlLoaderExtensions.split(', ')
config.resolveExtensions = config.strResolveExtensions.split(', ')
config.dllModules = config.strDllModule.split('\n').map(e => e.trim()).filter(e => e !== '')
config.dllModules = config.dllModules.concat(projectDllModules)

// Webpack fails if a dll module is repeated.
config.dllModules = config.dllModules.filter((value, index, self) =>
  self.indexOf(value) === index
)

config.libraryFiles = []
if (config.strLibraryFiles) {
  config.libraryFiles = config.strLibraryFiles.split('\n').map(e => e.trim()).filter(e => e !== '')
  config.libraryFiles = config.libraryFiles.filter((value, index, self) =>
    self.indexOf(value) === index
  )
}

if (!config.strProgressiveWebAppCacheFiles) {
  config.progressiveWebAppCacheFiles = []
} else {
  config.progressiveWebAppCacheFiles = config.strProgressiveWebAppCacheFiles.split('\n').map(e => e.trim()).filter(e => e !== '')
  config.progressiveWebAppCacheFiles = config.progressiveWebAppCacheFiles.map(e => {
    if (e.charAt(0) === '/') {
      return `${config.buildDir}${e}`
    }
    return `${config.buildDir}/${e}`
  })
}

config.testDirectory = 'test'

// At this time, the build directory must be directly below the vscode directory.
config.absoluteBuildPath = path.join(config.basePath, config.buildDir)
config.absoluteBuildScriptsPath = path.join(config.absoluteBuildPath, config.buildScriptDir)
config.absoluteDevToolsPath = path.join(config.basePath, 'devtools')

// At this time, the dll directory must be directly below the vscode directory.
config.absoluteDllPath = path.join(config.basePath, config.dllDir)

// Set the program entry point of your development/debug environents
if (config.useTypeScript) {
  if (process.env.NODE_ENV === 'production') {
    config.entryJs = 'index.tsx'
  } else {
    config.entryJs = 'index.dev.tsx'
  }
} else {
  if (process.env.NODE_ENV === 'production') {
    config.entryJs = 'index.js'
  } else {
    config.entryJs = 'index.dev.js'
  }
}

module.exports = config
